application: heavymetalab
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- appstats: on
- datastore_admin: on

handlers:
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /static
  static_dir: static

- url: /.*
  script: views.py

