application: heavymetalab
version: 1
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^.*/solr/.*

builtins:
- remote_api: on
- appstats: on
- datastore_admin: on

handlers:
- url: /static
  static_dir: sirc/fe/static
  expiration: "1m"

- url: /.*
  script: gae.py

